### ISSUE TITLE
Issue in deleting folder/file immediately after its creation.

### ISSUE THREAD

**Issue by NawafSwe** [hobigo/nextcloud-node-client#138]
I am trying to do unit testing using Jest to test functions of creating folder and deleting folder from the next cloud. 
I can create the file/folder successfully but when I end the test to delete it immediately I got an error says 

``` js 
{
  code: 'ERR_UNEXPECTED_HTTP_STATUS',
      context: {
        expectedHttpStatusCodes: [ 204 ],
        responseStatus: 423,
        responseStatusText: 'Locked'
      }
}
```

I think the reason is that the file is locked and needs some time to be able to delete it, I tried many solutions but did not worked out. 
Is there any option can I include in the body request to override this rule?.

**Comment by hobigo** [comment]
Hi,
I would assume that this is the desired behaviour from HTTP perspective. 204 indicates the the request has been accepted.
I have to check the API. The node client should retry and wait until the background operation has finished.
Maybe this behaviour is caused by a slow connection or a slow nextcloud server.

I will have a look at it.

**Comment by NawafSwe** [comment]
Thank you for your response I have sloved the problem.
